Fix build errors related to "parameter name omitted"
The following compilation errors occurred when compiling
on openSUSE Leap:

vpi_dummy.c: In function ‘vpi_printf’:
vpi_dummy.c:9:1: error: parameter name omitted
 PLI_INT32 vpi_printf(const char *, ...) {return 0;}
 ^~~~~~~~~

This was fixed with the changes from this commit.