Fix linker error	"undefined reference to symbol 'exp@@GLIBC_2.29'" on non Windows hosts
The command line to compile is
   CFLAGS="-Wall -Wextra -Werror -Wno-error=unused-but-set-variable" \
   ./configure \
    --with-x --with-readline=yes --enable-xspice \
     --enable-cider --enable-openmp --enable-osdi --enable-predictor